Allow marking sender to never show images
tutao/tutanota pull request #3176
Opened 2021-06-08 15:08 UTC by johnbotris

This depends on #3175

closes #3146

2021-07-21 11:07 UTC, vitoreiji requested changes
I noticed this doesn't implement "an option in settings where a user can see trusted and blocked external senders" as proposed in the issue. Has this been decided against? If not, then maybe we could just release it like this and postpone implementing the list. Otherwise, maybe we could consider hashing instead of encrypting.

2021-07-28 10:12 UTC, johnbotris commented on src/mail/view/MailViewer.js
> +		                                      .catch(e => ExternalImageRule.None)
it should only be dberrors in this case, but it's just for safety

2021-07-28 10:13 UTC, johnbotris commented on src/mail/view/MailViewer.js
> +		if (this._contentBlockingStatus !== ContentBlockingStatus.Block) {
it should be!

2021-07-28 10:14 UTC, johnbotris commented on src/mail/view/MailViewer.js
> +			? [ moreButton(alwaysOrNeverAllowButtons, 216) ]
width of the dropdown

2021-07-28 10:15 UTC, johnbotris commented on src/mail/view/MailViewer.js
> +			worker.addExternalImageRule(this.mail.sender.address, ExternalImageRule.None).catch(IndexingNotSupportedError, noOp)
not available yet!

2021-07-28 10:17 UTC, johnbotris commented
> I noticed this doesn't implement "an option in settings where a user can see trusted and blocked external senders" as proposed in the issue. Has this been decided against? If not, then maybe we could just release it like this and postpone implementing the list. Otherwise, maybe we could consider hashing instead of encrypting.

IMO it would be a good thing to have in the future

2021-08-02 14:43 UTC, charlag commented
What's the status? Needs to be reviewed again?

2021-08-02 15:24 UTC, charlag approved these changes

2021-08-03 10:14 UTC, merged