Update Flow. Remove Bluebird
tutao/tutanota pull request #3215
Opened 2021-06-24 14:22 UTC by charlag

Close #2725
Depends on oxmsg branch, see https://github.com/tutao/oxmsg/pull/2/

Code generator & admin updated in flow-bluebird branch.

2021-07-15 15:52 UTC, johnbotris commented
OXMSG changes have been published, so we can change the dependency to `"oxmsg": "0.0.7"`

2021-07-16 15:29 UTC, johnbotris requested changes
Looks good besides the things pointed out.
Some thoughts:
* It could be good to have some kind of wrapper that gives us `Promise.isPending()`/`Promise.isFulfilled()` type functionality since we use that pattern in a few places still
* We have `PromiseUtils.tap` for some of the `Promise.tap` replacements (lots of `.then(it => ...; return it)`)
* an `ofClass` that accepts multiple classes could be useful
* Replacements of `Promise.each` with `promiseMap` could probably be better off as for-each loops (although we could introduce concurrency more easily if we leave it?)
* lots of `return promiseMap(...).then(noOp)` which could also just be for-each  loops, or just `await` and drop the `then`

(I recognize the last two were probably from find/replace and it's probably more effort than it's worth to fix)

2021-07-16 15:29 UTC, johnbotris commented on make.js
> -	spawn(flow, ["--quiet"], {stdio: "inherit"}).on("exit", resolve).on("error", reject)
i like it better when it's quiet

2021-07-16 15:29 UTC, johnbotris commented on package.json
> +		"@tutao/oxmsg": "https://github.com/tutao/oxmsg.git#6e704f571b2307bb91e9af1020624a02b85b3f33",
`"@tutao/oxmsg": "0.0.7"`

2021-07-21 13:17 UTC, vitoreiji commented on src/desktop/DesktopDownloadManager.js
> +	async downloadNative(sourceUrl: string, fileName: string, headers: {|v: string, accessToken: string|}): Promise<{statusCode: string, statusMessage: string, encryptedFileUri: string}> {
I guess explicit exact or inexact notation is still recommended.
- https://medium.com/flow-type/on-the-roadmap-exact-objects-by-default-16b72933c5cf
- https://github.com/facebook/flow/releases/tag/v0.112.0

2021-08-02 07:51 UTC, charlag commented
>     * It could be good to have some kind of wrapper that gives us `Promise.isPending()`/`Promise.isFulfilled()` type functionality since we use that pattern in a few places still

We considered that but we could get away without it. I actually think that a proper state machine is better than checking things on promises in most cases.

>     * We have `PromiseUtils.tap` for some of the `Promise.tap` replacements (lots of `.then(it => ...; return it)`)

We have but I'm not sure if it's less wordy or not. Maybe it's less error-prone at least

>     * an `ofClass` that accepts multiple classes could be useful

I think we are already abusing exceptions for business logic and I would love us to do it less. If you need multiple exceptions just use `instanceof` manually.

>     * Replacements of `Promise.each` with `promiseMap` could probably be better off as for-each loops (although we could introduce concurrency more easily if we leave it?)

I'm not sure I understand your point. You propose to not use `promiseMap` and just write for loop each time?

2021-08-03 13:24 UTC, johnbotris approved these changes

2021-08-11 09:23 UTC, merged