WIP: Webauthn
tutao/tutanota pull request #3709
Opened 2021-11-30 16:54 UTC by charlag

2021-12-08 16:52 UTC, charlag commented
There seems to be an issue with picking a library. I used cbor-x but there's a wild `new Function()` in the middle of it which makes me uneasy.

There are also cborg and @stablelib/cbor but they both don't ship single file with decoder. We will either have to precompile/save directory (for cborg) or take both encoder and decoder (stablelib)

2021-12-09 12:13 UTC, charlag commented
I've replaced cbor-x with cborg but I had to rollup it first. It seems to be a solid, boring library

2021-12-20 10:25 UTC, johnbotris requested changes
Looks good besides small changes + your own notes

2021-12-20 10:25 UTC, johnbotris commented on src/misc/ErrorHandler.js
> +function throttledImport<R>(ms: number, fn: (() => Promise<R>)): (() => Promise<R>) {
Should comment what this is solving

2021-12-20 10:25 UTC, johnbotris commented on src/misc/ErrorHandler.js
>  		// decoupled to remove size of boot bundle
It would also be nice to make this comment more prominent as a doc comment at the top explaining why this file exists in the first place

2021-12-20 10:25 UTC, johnbotris commented on src/translations/en.js
> +		// TODO: translate
TODO

2021-12-20 17:18 UTC, merged