Set correct owner and type for events in shared calendars, #fix3762
tutao/tutanota pull request #4096
Opened 2022-05-03 13:08 UTC by sarashub

For the owner of a shared calendar the type of an event that was created
by  another user was wrongfully set to 'invite'.
To prevent this behavior we set the organizer of such events to be the
owner of the calendar as only the owner should be able to add guests anyways.

close #3762

2022-05-06 13:27 UTC, ganthern requested changes
* [x] smoke tested
* [x] good commit message
* [ ] doc comments where necessary
* [ ] ~commits are squashed appropriately~
* [x] sufficient test notes
* [x] changes reviewed
* [ ] ~translation keys are in Phrase~

besides the code comments, the commit message title line seems broken (`#fix3762` instead of `fix #3762`, which should be in the last line of the message)

2022-05-09 07:10 UTC, charlag commented on src/calendar/date/CalendarEventViewModel.ts
> +		// But we don't want to allow editing the event to make it more understandable for everyone.
Doc comments are about the interface mostly, this is about how it works, it's not useful to know when it happens for those who use it

2022-05-10 06:39 UTC, sarashub commented on src/calendar/date/CalendarEventViewModel.ts
> +	 *     owner of the calendar.
There is a four-star note on organizer.

2022-05-12 07:19 UTC, charlag commented on src/calendar/date/CalendarEventViewModel.ts
> +	private initOrganizer(existingOrganizer: EncryptedMailAddress | null, mailboxDetail: MailboxDetail, userController: IUserController): EncryptedMailAddress {
This can go now?

2022-05-12 07:21 UTC, sarashub commented on src/calendar/date/CalendarEventViewModel.ts
> +	private initOrganizer(existingOrganizer: EncryptedMailAddress | null, mailboxDetail: MailboxDetail, userController: IUserController): EncryptedMailAddress {
yes!

2022-05-12 08:03 UTC, charlag approved these changes
LGTM!
There's a "guests" dropdown that doesn't do anything but I think it's not a big issue.

2022-05-17 07:31 UTC, merged