add ctrl + A shortcut and tooltip to select all checkbox
tutao/tutanota pull request #5363
Opened 2023-04-12 14:22 UTC by ganthern

2023-04-13 07:16 UTC, charlag commented
People do use Ctrl-A to select all text in the mail, it would conflict, we should look for another one

2023-04-13 07:58 UTC, ganthern commented
that does not work for firefox at least, but we can still use something else

2023-04-18 11:14 UTC, charlag requested changes

2023-04-18 11:44 UTC, ganthern commented on src/gui/base/List.ts
> +			enabled: mapLazily(list, (list) => isDesktop() && list.config.multiSelectionAllowed),
it also shadows the search in tabs shortcut in chrome and in safari

2023-04-18 14:40 UTC, charlag commented on src/gui/base/List.ts
> +			enabled: mapLazily(list, (list) => isDesktop() && list.config.multiSelectionAllowed),
then let's come up with something bespoke and random, like "O" for calendar

2023-04-19 09:47 UTC, charlag approved these changes

2023-04-19 09:52 UTC, merged