[ios] Zip file when attaching if it is secretly a directory
tutao/tutanota pull request #5946
Opened 2023-09-29 13:53 UTC by wrdhub

Throw error instead of crashing when not able to handle file

#5209

2023-09-29 14:08 UTC, charlag requested changes
Commit message is outdated now I think

2023-09-29 14:08 UTC, charlag commented on app-ios/tutanota/Sources/Files/BlobUtil.swift
> +    let fileHandle = FileHandle(forReadingAtPath: fileUri)
I would use `guard let fileHandle = ...` instead but it's not that important

2023-09-29 14:08 UTC, charlag commented on app-ios/tutanota/Sources/Files/IosFileFacade.swift
> +        guard let destinationPath = try? zipFile(fileUrl: fileUrl) else {
I don't think we should quietly swallow these errors, we should rethrow it (with just `try`)

2023-09-29 14:08 UTC, charlag commented on app-ios/tutanota/Sources/Files/IosFileFacade.swift
> +  func zipFile(fileUrl: URL) throws -> String {
it's not necessarily a file I guess?

2023-09-29 14:16 UTC, wrdhub commented
> Commit message is outdated now I think

No, it still throws an error instead of crashing, I just decided to also handle zipping.

2023-10-02 07:30 UTC, charlag approved these changes

2023-11-01 13:12 UTC, merged