Show new event button in Agenda view when it's empty (for single and two columns layout)
tutao/tutanota pull request #7143
Opened 2024-07-01 07:37 UTC by andrehgdias

Closes #7139 
![image](https://github.com/tutao/tutanota/assets/44059355/0a547a9d-8f99-49c0-91f0-38aac9856cf4)

2024-07-09 07:26 UTC, murilopereirame commented on src/gui/base/buttons/BaseButton.ts
> +export function renderNewEventButton(buttonAttrs: { label: TranslationKey; click: ClickHandler; style?: Record<string, any> }): Children {
The name should be more generic in this case since this button is also used to create a new email.

2024-07-09 07:26 UTC, murilopereirame commented on src/gui/base/buttons/BaseButton.ts
> +export function renderNewEventButton(buttonAttrs: { label: TranslationKey; click: ClickHandler; style?: Record<string, any> }): Children {
This isn't a base button, it's worthwhile to have it's own file

2024-07-09 07:26 UTC, murilopereirame commented on src/calendar/view/CalendarAgendaView.ts
> +						"margin-top": ".6rem",
We have some utility classes for sizing and margins that we should use to keep the spacing standardized, take a look at [main-styles.ts#L266](https://github.com/tutao/tutanota/blob/971c09f66b0055e5b1af7684db53b6265c4c5ab0/src/gui/main-styles.ts#L266)

2024-07-09 07:27 UTC, murilopereirame requested changes

2024-07-09 07:27 UTC, murilopereirame commented on src/calendar/view/CalendarAgendaView.ts
> +						"margin-top": ".6rem",
We have some utility classes for sizing and margins that we should use to keep the spacing standardized, take a look at [main-styles.ts#L266](https://github.com/tutao/tutanota/blob/971c09f66b0055e5b1af7684db53b6265c4c5ab0/src/gui/main-styles.ts#L266)

2024-07-10 12:36 UTC, murilopereirame approved these changes

2024-07-11 13:54 UTC, wrdhub approved these changes

2024-07-12 06:47 UTC, rih-tutao approved these changes

2024-07-19 08:48 UTC, closed without merging